import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Master Finance',
  description: 'Generated by create next app, Develope by Alejandro Urrea',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-home bg-cover bg-no-repeat m-0 p-0`}>{children}</body>
    </html>
  )
}
